export interface IUserInfo {
  email?: string
  idNumber?: string
  mobileNumber?: string
  fullName?: string
  birthPlace?: string
  idPhoto?: string
  idHoldingPhoto?: string
  education?: string
  maritalStatus?: string
  dependents?: string
  motherMaidenName?: string
  jobType?: string
  jobIndustry?: string
  jobPosition?: string
  employerName?: string
  workSince?: string
  monthlyIncome?: string
  businessPhone?: string
  businessAddress?: string
  residentialStatus?: string
  residentialHomePhone?: string
  residentialProvince?: string
  residentialCity?: string
  residentialDistrict?: string
  residentialVillage?: string
  residentialAddress?: string
  residentialZipCode?: string
  paymentBankCode?: string
  paymentBankName?: string
  paymentBankAccountNo?: string
  contactFullName?: string
  contactPhoneNumber?: string
  contactRelation?: string
  studentCardPhoto?: string
}
